spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/publishing
    username: mike
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  mvc:
    throwExceptionIfNoHandlerFound: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: milenix.app@gmail.com
    password: loiwzngbvtsdcryx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

file:
  upload-dir-article: static/images/article-images
  upload-dir-user: static/images/user-images

openai:
  api_key: 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
